### ISSUE TITLE
Netbox v4.2 compatibility

### ISSUE THREAD

**Issue by candlerb** [FlxPeters/netbox-prometheus-sd#93]
After updating Netbox from v4.1.11 to v4.2.3 I am getting these exceptions:

```
AttributeError at /api/plugins/prometheus-sd/devices/
'Cluster' object has no attribute 'site'

AttributeError at /api/plugins/prometheus-sd/virtual-machines/
Cannot find 'site' on Cluster object, 'cluster__site' is an invalid parameter to prefetch_related()
```

Same with either of these in `local_requirements.txt`:

* `netbox-plugin-prometheus-sd`
* `git+https://github.com/FlxPeters/netbox-plugin-prometheus-sd@main`

Backtraces:

```
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_prometheus_sd/api/serializers.py", line 47, in to_representation
    ret.append(self.child.to_representation(item))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_prometheus_sd/api/serializers.py", line 91, in get_labels
    utils.extract_cluster(obj, labels)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_prometheus_sd/api/utils.py", line 61, in extract_cluster
    if obj.cluster.site:
       ^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /api/plugins/prometheus-sd/devices/
Exception Value: 'Cluster' object has no attribute 'site'
Raised during: netbox_prometheus_sd.api.views.DeviceViewSet
```

```
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_prometheus_sd/api/serializers.py", line 26, in to_representation
    for item in iterable:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1930, in _fetch_all
    self._prefetch_related_objects()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1320, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/models/query.py", line 2355, in prefetch_related_objects
    raise AttributeError(
    ^

Exception Type: AttributeError at /api/plugins/prometheus-sd/virtual-machines/
Exception Value: Cannot find 'site' on Cluster object, 'cluster__site' is an invalid parameter to prefetch_related()
Raised during: netbox_prometheus_sd.api.views.VirtualMachineViewSet
```

According to "breaking changes" in the [release notes for v4.2.0](https://github.com/netbox-community/netbox/releases/v4.2.0):

>  The `site` foreign key field on `virtualization.Cluster` has been replaced by the `scope` generic foreign key.

**Comment by candlerb** [comment]
Quick temporary hack (directly under `/opt/netbox/venv/lib64/python3.12/site-packages/netbox_prometheus_sd`):

```
--- api/views.py.orig	2025-02-13 21:18:20.042972992 +0000
+++ api/views.py	2025-02-13 21:18:11.288947385 +0000
@@ -59,7 +59,7 @@

 class VirtualMachineViewSet(NetboxPrometheusSDModelViewSet):
     queryset = VirtualMachine.objects.prefetch_related(
-        "cluster__site",
+        "cluster",
         "role",
         "tenant",
         "platform",
--- api/utils.py.orig	2025-02-13 21:12:17.219046614 +0000
+++ api/utils.py	2025-02-13 21:12:53.027127539 +0000
@@ -58,9 +58,9 @@
             labels["cluster_group"] = obj.cluster.group.name
         if obj.cluster.type:
             labels["cluster_type"] = obj.cluster.type.name
-        if obj.cluster.site:
-            labels["site"] = obj.cluster.site.name
-            labels["site_slug"] = obj.cluster.site.slug
+        #if obj.cluster.site:
+        #    labels["site"] = obj.cluster.site.name
+        #    labels["site_slug"] = obj.cluster.site.slug

     # Has precedence over cluster site
     if hasattr(obj, "site") and obj.site is not None:
```

In the UI, it looks like the 'scope' GFK could point to location, site, site group or region.  If it's the first two, potentially a site could be extracted.

**Comment by candlerb** [comment]
Sorry, I posted this in the wrong repo. It should have been https://github.com/FlxPeters/netbox-plugin-prometheus-sd - but this issue has been fixed there already.
